title: Ryan D. Najac
description: "Welcome to my personal website!"
profile: assets/rdnajac-profile.jpg
favicon: assets/favicon.ico
tagline: "Researcher and programmer at the <a href='https://www.palomerolab.org/'>Palomero Lab</a>"

plugins:
  - jekyll-seo-tag
