title: "Ryan Najac"
description: "Hello, world!"
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/minima@v0.2.0
plugins:
- jekyll-remote-theme
